version: "3.9"

services:
  app-prod:
    image: ligary/garyli.dev:TorontoGQL
    pull_policy: always
    environment:
      SEQUELIZE_URL: postgres://postgres:abc123@db-prod:5432/postgres
      NODE_ENV: production
      APOLLO_PORT: 443
    links:
      - db-prod
    volumes:
      - /etc/letsencrypt:/ssl
    ports:
      - "443:443"

  db-prod:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: abc123
