version: "3.9"

services:
  app-dev:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    environment:
      SEQUELIZE_URL: postgres://postgres:abc123@localhost:5432/postgres
      NODE_ENV: dev
    network_mode: service:db-dev
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  db-dev:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: abc123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
volumes:
  postgres-data:
